### ISSUE TITLE
【ERROR】Unhandled rejection TypeError: Cannot read property 'timestamp' of null

### ISSUE THREAD

**Issue by fiattt** [EOSIO/genesis#26]
use code: 
Commit: 46bfea2d56b89f856ddad1101409eec67e14a635
Date:26 March 2018 at 7:01:11 AM

Parity://v1.7.8-stable-d5fcf3b-20171025/x86_64-macos/rustc1.21.0

first time i set period 280 get the error message
then i set period 10. it ok.  
it seems that  the larger the syncing period range the greater the chance of get the error  

![ae3b0c13bef9bfad4158dbfc95260923](https://user-images.githubusercontent.com/1531440/38006645-8b1e43f6-3278-11e8-88d4-88db5d2f9389.png)

**Comment by fiattt** [comment]
when parity restoring from a snapshot it will discard downloaded blocks cause this null
it will fix in parity1.11
https://github.com/paritytech/parity/issues/8079
https://github.com/paritytech/parity/issues/6350
https://github.com/paritytech/parity/milestone/20

work around:
https://github.com/fiattt/genesis/commit/92846782c2432d199abeb8e3b5e5903cd299121e

**Comment by dskvr** [comment]
@fiatt please read the instructions carefully. It sounds like you ran the snapshot without --no-warp. This instructions clearly state this is what will happen if you run a warped chain.

**Comment by dskvr** [comment]
Also @fiattt your suggested fix will not produce an accurate snapshot.

**Comment by fiattt** [comment]
@dskvr tks, I deleted the work around. 

finally succeed use the following steps：
0. my environment：Mac
1. clean my data. delete ~/Library/Application Support/io.parity.ethereum
2. use the "brew install parity"（Parity v1.9.5-20180321 stable）instead of parity_xxx_macos_macos.pkg install
3. run "parity --no-warp" to start and synchronize all blocks
4. when the synchronization is complete Ctrl+c to close parity
**5. run "parity --no-warp --mode=offline" to start a offline parity**
6. finally run "node snapshot.js" 

<img width="502" alt="5b5f4afa-59a0-4675-b5c0-4f853076d779" src="https://user-images.githubusercontent.com/1531440/39027143-1b38981c-4483-11e8-9092-7a8cbe4a3a81.png">
