### ISSUE TITLE
Margin of Error in Period 0 is too high

### ISSUE THREAD

**Issue by dskvr** [EOSIO/genesis#38]
This could be a signal that unclaimed balance calculations are inaccurate, that there is a logical error with handling of period 0, that period map is not handling period 0 correctly or that the margin of error calculation is erroneous. 

Debugging:
- No users should have a positive `wallet balance` in period 0
- If above is true, check unclaimed logic, randomly sample period 0 wallets and manually calculate their unclaimed transactions. 

Tests required
- Write a test that triggers if `config.period=0` that asserts `select count(*) from wallets where balance_wallet>0` returns `0`
- Write a test that randomly samples `n` users with unclaimed balances (from any period) and calculates their unclaimed balance inline without utilizing existing balance utility.

**Comment by rohanabraham** [comment]
I got this error for Period 0, not sure if it is related.
![image](https://user-images.githubusercontent.com/4366633/39836526-a49bd3c4-53cb-11e8-9bc7-0ec348523ec1.png)

**Comment by dskvr** [comment]
@rohanabraham That's not related, that's related to the resume functionality in the alpha optimizations branch.

**Comment by dskvr** [comment]
I've found and resolved this issue, it will be included in the beta tag.
