### ISSUE TITLE
【Error】Error: Invalid UTF-8 detected

### ISSUE THREAD

**Issue by fiattt** [EOSIO/genesis#43]
use code:
Commit: 8dc37be59bfa9c898c4f3c7ba51d282fd0cddd96
May 15, 2018 at 7:34:06 PM GMT+8

throw error: "Unhandled rejection Error: Error: Invalid UTF-8 detected"

detail:
![image](https://user-images.githubusercontent.com/1531440/40107331-87342502-592a-11e8-9ebf-f8d79582e67e.png)

**Comment by dskvr** [comment]
@fiattt As mentioned at the top of the readme, this issue is addressed in another branch in progress. Please read the top of the readme and the attached issue. Also be aware, master is out of date.
