### ISSUE TITLE
I've sent Eos token to Eos Evolution Token Contract Address. Please give it back.

### ISSUE THREAD

**Issue by jihee1223** [EOSIO/genesis#49]
Please don't destroy other person's life. Please don't kill me. 

I say to you again. Please transmit back my Eos 814.90796034 token in my wallet. as soon as possible.

I tried to transmit Eos 814.90796034 token into my own wallet address. but they have been wrong transmitted to Eos Evolution Token Contract Address. 

This is the record picture of  etherscan. My wallet address is [0xf1125056e29DF8C5527868ae0de70463e4F17522] . 

Please transmit back my Eos 814.90796034 token there. 

 Please look at the attached photo.
![etherscan1](https://user-images.githubusercontent.com/39737784/40667200-817daf26-639c-11e8-8d56-4a8e203aabe0.JPG)
![etherscan2](https://user-images.githubusercontent.com/39737784/40667201-82092a88-639c-11e8-9218-78c2751d0b32.JPG)

**Comment by dskvr** [comment]
Other that being hyperbolic, you're a bit mistaken, it's not me who solely decides you're fate. What decides the math on the snapshot is **objective parameters**. What you're requesting is a **subjective parameter** and would be difficult to justify. Once a single subjective exception is included in the script, it opens the doors for thousands of others, and becomes an impossible to verify situation. 

Again, consider arbitration on an EOSIO network.
